name = "backend"
compatibility_date = "2023-12-01"

[vars]

DATABASE_URL = "your_database_url_here" #replace with your own database url

JWT_SECRET = "my-jwt-secret" #replace with your own secret



# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"